import importlib.util

from lupa.luajit21 import LuaRuntime

from conftest import MOD_DIR, ROOT

COMMITTED = MOD_DIR / "donation_army_rosters.lua"


def load_generator():
    spec = importlib.util.spec_from_file_location("gen_rosters", ROOT / "tools/gen_rosters.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_rosters(text):
    lua = LuaRuntime(unpack_returned_tuples=True)
    lua.execute(text)
    return lua, lua.globals().donation_army_rosters


def test_committed_rosters_match_generator(tmp_path):
    out = tmp_path / "rosters.lua"
    load_generator().main([str(out)])
    # compare text (universal newlines), not bytes: git may check the committed file out with CRLF
    expected = COMMITTED.read_text(encoding="utf-8")
    assert out.read_text(encoding="utf-8") == expected, "run `python tools/gen_rosters.py` and commit the result"


def test_header_marks_file_generated():
    first = COMMITTED.read_text(encoding="utf-8").splitlines()[0]
    assert "generated by tools/gen_rosters.py" in first and "do not edit" in first


def test_all_23_races_with_faction_keys():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    races = sorted(rosters.keys())
    assert len(races) == 23
    assert rosters["chs"].faction == "wh_main_chs_chaos_qb1"
    assert rosters["nor"].faction == "wh_main_nor_norsca_qb1"
    assert rosters["skv"].faction == "wh2_main_skv_skaven_qb1"


def test_only_vanilla_units_lords_heroes():
    text = COMMITTED.read_text(encoding="utf-8")
    assert "ghs_" not in text  # non-vanilla (Great Harmony) avatars in the source data
    lua, rosters = load_rosters(text)
    skv = rosters["skv"]
    assert "wh2_main_skv_inf_clanrats_0" in list(skv.units[1].melee_infantry.values())
    heroes = [(h.agent_type, h.agent_subtype) for h in skv.heroes.values()]
    assert ("champion", "wh2_dlc16_skv_chieftain") in heroes
    assert "wh2_main_skv_warlord" in list(skv.lords.values())


def test_lords_and_heroes_unique_and_sorted():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    for race in rosters.keys():
        lords = list(rosters[race].lords.values())
        assert lords and lords == sorted(set(lords)), race
        heroes = [(h.agent_type, h.agent_subtype) for h in rosters[race].heroes.values()]
        assert heroes == sorted(set(heroes)), race
