import importlib.util

import pytest
from lupa.luajit21 import LuaRuntime

from conftest import MOD_DIR, ROOT

COMMITTED = MOD_DIR / "donation_army_rosters.lua"


def load_generator():
    spec = importlib.util.spec_from_file_location("gen_rosters", ROOT / "tools/gen_rosters.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_rosters(text):
    lua = LuaRuntime(unpack_returned_tuples=True)
    lua.execute(text)
    return lua, lua.globals().donation_army_rosters


def test_committed_rosters_match_generator(tmp_path):
    if not (ROOT / "main_units_tables.tsv").exists():
        pytest.skip("main_units_tables.tsv (gitignored RPFM export) absent: generator output differs without table validation")
    out = tmp_path / "rosters.lua"
    load_generator().main([str(out)])
    # compare text (universal newlines), not bytes: git may check the committed file out with CRLF
    expected = COMMITTED.read_text(encoding="utf-8")
    assert out.read_text(encoding="utf-8") == expected, "run `python tools/gen_rosters.py` and commit the result"


def test_header_marks_file_generated():
    first = COMMITTED.read_text(encoding="utf-8").splitlines()[0]
    assert "generated by tools/gen_rosters.py" in first and "do not edit" in first


def test_all_23_races_with_faction_keys():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    races = sorted(rosters.keys())
    assert len(races) == 23
    assert rosters["chs"].faction == "wh_main_chs_chaos_qb1"
    assert rosters["nor"].faction == "wh_main_nor_norsca_qb1"
    assert rosters["skv"].faction == "wh2_main_skv_skaven_qb1"


def test_only_vanilla_units_lords_heroes():
    text = COMMITTED.read_text(encoding="utf-8")
    assert "ghs_" not in text  # non-vanilla (Great Harmony) avatars in the source data
    lua, rosters = load_rosters(text)
    skv = rosters["skv"]
    assert "wh2_main_skv_inf_clanrats_0" in list(skv.units[1].melee_infantry.values())
    heroes = [(h.agent_type, h.agent_subtype) for g in skv.heroes.values() for h in g.values()]
    assert ("champion", "wh2_dlc16_skv_chieftain") in heroes
    assert "wh2_main_skv_warlord" in [s for g in skv.lords.values() for s in g.values()]


def test_lords_and_heroes_unique_and_sorted():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    for race in rosters.keys():
        lords = [s for g in rosters[race].lords.values() for s in g.values()]
        assert lords and len(lords) == len(set(lords)), race
        heroes = [(h.agent_type, h.agent_subtype) for g in rosters[race].heroes.values() for h in g.values()]
        assert len(heroes) == len(set(heroes)), race
        assert all(len(g) > 0 for g in rosters[race].lords.values()), race


def lord_groups(rosters, race):
    return [sorted(g.values()) for g in rosters[race].lords.values()]


def test_lore_variants_share_a_lord_group():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    for race, prefix, size in [("hef", "wh2_dlc15_hef_archmage_", 9), ("lzd", "wh2_dlc13_lzd_slann_mage_priest_", 7),
                               ("bst", "wh2_twa04_bst_great_bray_shaman_", 4), ("brt", "wh_dlc07_brt_prophetess_", 3),
                               ("wef", "wh2_dlc16_wef_spellweaver_", 5), ("def", "wh2_dlc10_def_supreme_sorceress_", 5)]:
        group = next(g for g in lord_groups(rosters, race) if any(s.startswith(prefix) for s in g))
        assert sum(s.startswith(prefix) for s in group) == size, race
    # the plain slann lands with the lores
    slann = next(g for g in lord_groups(rosters, "lzd") if "wh2_main_lzd_slann_mage_priest" in g)
    assert "wh2_dlc13_lzd_slann_mage_priest_life" in slann


def test_lord_group_counts_keep_archetypes_distinct():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    counts = {race: len(lord_groups(rosters, race)) for race in rosters.keys()}
    assert counts["brt"] == 2 and counts["bst"] == 3 and counts["hef"] == 3 and counts["chs"] == 3
    assert counts["skv"] == 4 and counts["cth"] == 3 and counts["ogr"] == 2 and counts["tze"] == 2
    # chs lord marks collapse into one lord group, and Daemon Princes stay apart from sorcerer lords
    chs = lord_groups(rosters, "chs")
    assert any("wh_main_chs_lord" in g and "wh3_dlc25_chs_lord_mnur" in g for g in chs)
    assert not any("wh_main_chs_lord" in g and any("sorcerer_lord" in s for s in g) for g in chs)


def roster_unit_keys(rosters):
    for race in rosters.keys():
        for roles in rosters[race].units.values():
            for keys in roles.values():
                for key in keys.values():
                    yield race, key


def test_no_roster_unit_matches_name_filter():
    gen = load_generator()
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    bad = [(r, k) for r, k in roster_unit_keys(rosters) if gen.name_excluded(k)]
    assert not bad, bad
    assert all(not gen.name_excluded(k) for r in rosters.keys() for k in rosters[r].costs.keys())


def test_name_filter_patterns():
    gen = load_generator()
    for key in ["wh_dlc08_vmp_mon_terrorgheist_boss", "wh3_dlc27_bst_mon_ghorgon_boss_x", "wh3_dlc25_dwf_inf_slayers_grudge_unit",
                "wh_main_emp_veh_steam_tank_driver", "wh_main_vmp_mon_terrorgheist_qb", "wh3_dlc24_qb_cst_cav_knights_errant_0"]:
        assert gen.name_excluded(key), key
    assert not gen.name_excluded("wh_main_vmp_mon_terrorgheist")


def test_roster_units_exist_in_main_units_table():
    tsv = ROOT / "main_units_tables.tsv"
    if not tsv.exists():
        pytest.skip("main_units_tables.tsv (gitignored RPFM export) absent")
    valid = load_generator().read_tsv_keys(tsv, "unit")
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    missing = [(r, k) for r, k in roster_unit_keys(rosters) if k not in valid]
    assert not missing, missing


def test_vampire_counts_keeps_monsters_and_no_boss_terrorgheist():
    _, rosters = load_rosters(COMMITTED.read_text(encoding="utf-8"))
    keys = {k for r, k in roster_unit_keys(rosters) if r == "vmp"}
    assert "wh_dlc08_vmp_mon_terrorgheist_boss" not in keys
    assert any(role == "monster" for tier in rosters["vmp"].units.values() for role in tier.keys())
