-- Donation Army settings. Edit tiers freely: the highest min_usd a donation meets wins.
-- Each spawn picks a random race from `races`, then builds a random army for the tier's difficulty from that
-- race's roster (donation_army_rosters.lua, generated by tools/gen_rosters.py from Land Encounters and Points of
-- Interest data). Armies are spawned as CA invasions that hunt the player.
-- An army holds at most 20 units including its lord and heroes.

donation_army_config = {
	queue_file = "donation_army_queue.txt", -- relative to the WH3 install folder
	poll_interval_ms = 10000,
	spawn_distance = 5,
	-- effect bundle applied to every spawned army for its lifetime (no regionless attrition, no upkeep); "" disables
	army_effect_bundle = "wh2_dlc16_bundle_military_upkeep_free_force_immune_to_regionless_attrition",
	-- from that turn on, every donation spawns that many tiers higher, capped at the top tier; set to {} to disable
	turn_tier_bonus = { { turn = 5, tiers = 1 }, { turn = 30, tiers = 2 } },
	-- races an army may be rolled from (keys of donation_army_rosters, e.g. { "chs", "skv", "emp" }); nil = all
	races = nil,
	tiers = {
		{ name = "Warband", min_usd = 5, difficulty = "easy" },
		{ name = "Horde", min_usd = 20, difficulty = "medium" },
		{ name = "Doomstack", min_usd = 50, difficulty = "hard" },
	},
	-- army generation per difficulty: unit tiers (1-5), army size incl. lord and heroes, unit xp ranks,
	-- lord level, and per-role {min, max} counts (infantry min/max is the core; other roles only use max)
	difficulties = {
		easy = {
			tiers = { 1, 2 }, min_units = 10, max_units = 13, unit_xp = { 1, 3 }, lord_level = { 5, 10 },
			limits = {
				hero = { 0, 0 }, melee_infantry = { 3, 6 }, missile_infantry = { 0, 3 },
				melee_cavalry = { 0, 2 }, missile_cavalry = { 0, 2 }, monstrous_infantry = { 0, 2 },
				monstrous_cavalry = { 0, 2 }, war_beast = { 0, 2 },
				chariot = { 0, 0 }, warmachine = { 0, 0 }, monster = { 0, 0 }, generic = { 0, 0 },
			},
		},
		medium = {
			tiers = { 1, 3 }, min_units = 14, max_units = 16, unit_xp = { 3, 5 }, lord_level = { 10, 15 },
			limits = {
				hero = { 0, 1 }, melee_infantry = { 3, 5 }, missile_infantry = { 0, 3 },
				melee_cavalry = { 0, 2 }, missile_cavalry = { 0, 2 }, monstrous_infantry = { 0, 2 },
				monstrous_cavalry = { 0, 2 }, war_beast = { 0, 2 },
				chariot = { 0, 1 }, warmachine = { 0, 1 }, monster = { 0, 1 }, generic = { 0, 1 },
			},
		},
		hard = {
			tiers = { 1, 5 }, min_units = 17, max_units = 20, unit_xp = { 5, 7 }, lord_level = { 15, 20 },
			limits = {
				hero = { 0, 2 }, melee_infantry = { 4, 6 }, missile_infantry = { 2, 4 },
				melee_cavalry = { 0, 2 }, missile_cavalry = { 0, 2 }, monstrous_infantry = { 0, 2 },
				monstrous_cavalry = { 0, 2 }, war_beast = { 0, 2 },
				chariot = { 0, 1 }, warmachine = { 0, 1 }, monster = { 0, 1 }, generic = { 0, 1 },
			},
		},
	},
}
