"""Generate mod/script/campaign/mod/donation_army_rosters.lua from the vendored Land Encounters data.

Usage: python tools/gen_rosters.py [output_path]

Keeps only origin == "vanilla" units, lords and heroes; maps each race shorthand to the
quest-battle (_qb1) faction proven to exist in Immortal Empires; drops races with no lords or no infantry.
Each unit's gold cost (multiplayer_cost, else recruitment_cost; the highest if the data lists it twice) goes in
the race's `costs` map, used by the composer's per-difficulty min_unit_cost.
"""
import pathlib
import re
import sys

from lupa.luajit21 import LuaRuntime

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / "tools/data/land_encounters_factions_data.lua"
OUT = ROOT / "mod/script/campaign/mod/donation_army_rosters.lua"

FACTIONS = {
    "brt": "wh_main_brt_bretonnia_qb1",
    "bst": "wh_dlc03_bst_beastmen_qb1",
    "chd": "wh3_dlc23_chd_chaos_dwarfs_qb1",
    "chs": "wh_main_chs_chaos_qb1",
    "cst": "wh2_dlc11_cst_vampire_coast_qb1",
    "cth": "wh3_main_cth_cathay_qb1",
    "def": "wh2_main_def_dark_elves_qb1",
    "dwf": "wh_main_dwf_dwarfs_qb1",
    "emp": "wh_main_emp_empire_qb1",
    "grn": "wh_main_grn_greenskins_qb1",
    "hef": "wh2_main_hef_high_elves_qb1",
    "kho": "wh3_main_kho_khorne_qb1",
    "ksl": "wh3_main_ksl_kislev_qb1",
    "lzd": "wh2_main_lzd_lizardmen_qb1",
    "nor": "wh_main_nor_norsca_qb1",
    "nur": "wh3_main_nur_nurgle_qb1",
    "ogr": "wh3_main_ogr_ogre_kingdoms_qb1",
    "skv": "wh2_main_skv_skaven_qb1",
    "sla": "wh3_main_sla_slaanesh_qb1",
    "tmb": "wh2_dlc09_tmb_tombking_qb1",
    "tze": "wh3_main_tze_tzeentch_qb1",
    "vmp": "wh_main_vmp_vampire_counts_qb1",
    "wef": "wh_dlc05_wef_wood_elves_qb1",
}

ROLES = [
    "melee_infantry", "missile_infantry", "melee_cavalry", "missile_cavalry", "monstrous_infantry",
    "monstrous_cavalry", "chariot", "warmachine", "war_beast", "monster", "generic",
]

HEADER = (
    "-- generated by tools/gen_rosters.py from Land Encounters and Points of Interest data — do not edit\n"
    "-- race shorthand -> { faction, units[tier][role] = unit keys, costs[unit key] = gold cost, lords = { {subtype, ...}, ... } groups by type, heroes = { { {agent_type, agent_subtype}, ... }, ... } groups by type }\n"
)


# Lords and heroes are grouped into "types" so that a race's many per-lore caster subtypes (e.g. 9 high elf archmage
# lores, 8 slann lores) count as one type when picking. A subtype's key is its name split on "_" with the tokens below
# (lores, winds, Chaos marks, gender and variant markers) removed; subtypes with the same key share a group.
# Note "great" (great_maw, great_bray_shaman) and "maw" are stripped too, so a bare slann_mage_priest lands with its lores.
VARIANT_TOKENS = {
    "beasts", "heavens", "life", "death", "shadow", "shadows", "wild", "fire", "metal", "light", "high", "dark",
    "hashut", "vampires", "deep", "yin", "yang", "ice", "tempest", "plague", "ruin", "nurgle", "slaanesh",
    "tzeentch", "khorne", "undivided", "great", "maw", "mkho", "msla", "mnur", "mtze", "fem", "chaos", "cha",
    "nehekhara",
}


def type_key(subtype):
    tokens = [t for t in re.sub(r"^wh\d*_[a-z0-9]+_", "", subtype).split("_") if t not in VARIANT_TOKENS]
    if len(tokens) > 1 and tokens[-1] in tokens[:-1]:
        tokens.pop()
    return "_".join(tokens)


def group_by_type(items, key):
    groups = {}
    for item in items:
        groups.setdefault(type_key(key(item)), []).append(item)
    return [groups[k] for k in sorted(groups)]


def vanilla(entries):
    return [e for e in (entries or {}).values() if e["origin"] == "vanilla"]


# Units the source data files under a role that doesn't fit how they fight. Applied after loading, before the
# rosters are written; add `"unit_key": "role"` entries as needed (role must be one of ROLES).
ROLE_OVERRIDES = {
    # stealthy flankers filed as melee infantry; as melee infantry they became the Ogre infantry core
    "wh3_main_ogr_mon_gorgers_0": "monstrous_infantry",
}


def unit_cost(entry):
    return int(entry["multiplayer_cost"] or entry["recruitment_cost"] or 0)


def build(data):
    rosters = {}
    for race in sorted(data.keys()):
        if race not in FACTIONS:
            continue
        src = data[race]
        units, costs = {}, {}
        for tier_name in src["units"].keys():
            tier = int(tier_name.removeprefix("tier_"))
            by_role = {}
            for role in ROLES:
                for e in vanilla(src["units"][tier_name][role]):
                    costs[e["land_unit"]] = max(costs.get(e["land_unit"], 0), unit_cost(e))
                    by_role.setdefault(ROLE_OVERRIDES.get(e["land_unit"], role), set()).add(e["land_unit"])
            roles = {role: sorted(by_role[role]) for role in ROLES if by_role.get(role)}
            if roles:
                units[tier] = roles
        lords = group_by_type(sorted({e["agent_subtype"] for e in vanilla(src["allowed_lords"])}), lambda s: s)
        heroes = group_by_type(
            sorted({(e["agent_type"], e["agent_subtype"]) for e in vanilla(src["allowed_heroes"])}), lambda h: h[1]
        )
        has_infantry = any(r in roles for roles in units.values() for r in ("melee_infantry", "missile_infantry"))
        if lords and has_infantry:
            rosters[race] = {
                "faction": FACTIONS[race], "units": units, "costs": costs, "lords": lords, "heroes": heroes,
            }
    return rosters


def q(s):
    return '"' + s + '"'


def render(rosters):
    out = [HEADER, "donation_army_rosters = {\n"]
    for race, r in rosters.items():
        out.append(f"\t{race} = {{\n")
        out.append(f"\t\tfaction = {q(r['faction'])},\n")
        out.append("\t\tunits = {\n")
        for tier in sorted(r["units"]):
            out.append(f"\t\t\t[{tier}] = {{\n")
            for role in ROLES:
                if role in r["units"][tier]:
                    keys = ", ".join(q(k) for k in r["units"][tier][role])
                    out.append(f"\t\t\t\t{role} = {{ {keys} }},\n")
            out.append("\t\t\t},\n")
        out.append("\t\t},\n")
        out.append("\t\tcosts = {\n")
        for key in sorted(r["costs"]):
            out.append(f"\t\t\t{key} = {r['costs'][key]},\n")
        out.append("\t\t},\n")
        out.append("\t\tlords = {\n")
        for group in r["lords"]:
            out.append("\t\t\t{ " + ", ".join(q(s) for s in group) + " },\n")
        out.append("\t\t},\n")
        out.append("\t\theroes = {\n")
        for group in r["heroes"]:
            items = ", ".join(f"{{ agent_type = {q(t)}, agent_subtype = {q(s)} }}" for t, s in group)
            out.append(f"\t\t\t{{ {items} }},\n")
        out.append("\t\t},\n")
        out.append("\t},\n")
    out.append("}\n")
    return "".join(out)


def generate(data_path=DATA):
    lua = LuaRuntime(unpack_returned_tuples=True)
    data = lua.execute(pathlib.Path(data_path).read_text(encoding="utf-8"))
    return render(build(data))


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    out = pathlib.Path(argv[0]) if argv else OUT
    out.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
